// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// [DefaultFirebaseOptions]
/// This class provides the centralized configuration for Firebase across all supported platforms.
/// It ensures that the correct API keys and App IDs are used based on the device's operating system.
///
/// Usage:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNm9jpeL15VcOPsFnkXpHsBKPgcEMnQ5I',
    appId: '1:379839155492:web:1700e4c19721563f73b7b1',
    messagingSenderId: '379839155492',
    projectId: 'chat-app-59815',
    authDomain: 'chat-app-59815.firebaseapp.com',
    storageBucket: 'chat-app-59815.firebasestorage.app',
    measurementId: 'G-Q4K1G09TTZ',
  );

  // --- Web Configuration ---

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_mPNfb-QM-hr7l5BpjI2AmGNNnYZlJiw',
    appId: '1:379839155492:android:6be5861f8b875c7f73b7b1',
    messagingSenderId: '379839155492',
    projectId: 'chat-app-59815',
    storageBucket: 'chat-app-59815.firebasestorage.app',
  );

  // --- Android Configuration ---

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZHCUJWu0xF1FGR-PAm6CR4meWhV2FGA',
    appId: '1:379839155492:ios:69c001c7aa3382b673b7b1',
    messagingSenderId: '379839155492',
    projectId: 'chat-app-59815',
    storageBucket: 'chat-app-59815.firebasestorage.app',
    iosClientId: '379839155492-89omi7sh8kb1ka47aavf6k2m5384k28j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  // --- iOS Configuration ---

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbZHCUJWu0xF1FGR-PAm6CR4meWhV2FGA',
    appId: '1:379839155492:ios:69c001c7aa3382b673b7b1',
    messagingSenderId: '379839155492',
    projectId: 'chat-app-59815',
    storageBucket: 'chat-app-59815.firebasestorage.app',
    iosClientId: '379839155492-89omi7sh8kb1ka47aavf6k2m5384k28j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  // --- macOS Configuration ---

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNm9jpeL15VcOPsFnkXpHsBKPgcEMnQ5I',
    appId: '1:379839155492:web:f675c82d97e14a2d73b7b1',
    messagingSenderId: '379839155492',
    projectId: 'chat-app-59815',
    authDomain: 'chat-app-59815.firebaseapp.com',
    storageBucket: 'chat-app-59815.firebasestorage.app',
    measurementId: 'G-ERS86G35Q2',
  );

  // --- Windows Configuration ---
}